global:
  slack_api_url: "<Link from slack hooks configuration>"

route:
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 2m
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - channel: "#fleetman-alerts"
        icon_emoji: ":bell:"
        send_resolved: true
        text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}\nmessage: {{ .CommonAnnotations.message }}"
