# This deployement is intentionally created to trigger the alert manager
# Now those error alerts can be seen in the slack channel

# Only deploy this manifest if you want to test if alertmanager sends you alert messages on your configured slack channel 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment

metadata:
  name: error-deployment

spec:
  selector:
    matchLabels:
      app: bad
  replicas: 1
  template:
    metadata:
      labels:
        app: bad
    spec:
      containers:
        - name: bad
          image: ubuntu:18.04
          command: ["88 print('goro moro toro')hahahah"]
