apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fleetman
  region: ap-south-1

nodeGroups:
  - name: node-group-1
    # instanceType: t3.small # More CPU and Memory than t2.micro (consider this if you hit resource limits)
    desiredCapacity: 3
    minSize: 3
    maxSize: 10 # To allow some scaling if needed
    iam:
      instanceRoleARN: arn:aws:iam::<AWS account number>:role/<your role name>

addons:
  - name: aws-ebs-csi-driver
    version: latest
